### ISSUE TITLE
stock_info.get_live_price('VTSAX') returns 'nan'

### ISSUE THREAD

**Issue by khorton** [atreadw1492/yahoo_fin#15] opened 2020-09-06 02:59 UTC
VTSAX and VTIAX are returning NaN for stock_info.get_live_price and stock_info.get_data today (2020-09-05).

finance.yahoo.com has the latest data for these.  I'm not sure if Yahoo has a bug that broke yahoo_fin or whether the bug is in yahoo_fin.

Thanks for this module.  I was very happy to find it.

**Comment by atreadw1492** [comment] 2020-11-20 01:11
Hi @khorton - thanks for using yahoo_fin!  This is occurring because Yahoo Finance seems to update the quote page first, but the historical prices data is not yet updated for the current date for these two funds (and other mutual funds as well).  There is a slight workaround this, which will be included in the next package release.

**Closed by atreadw1492** 2020-11-20 01:11 UTC

**Comment by khorton** [comment] 2021-07-15 02:42
Did the "slight workaround" for these delays get into the package?  I'm still not getting any data for mutual funds for many hours after Yahoo shows price data on their web pages

**Comment by Distortedlogic** [comment] 2022-03-30 14:19
bump

**Comment by leetorres** [comment] 2024-10-12 00:11
get_live_price is returning nan because for the current date, there isn't a price in the Yahoo Fin database. But there is likely a price in previous days.

If get_live_price returns nan, an alternative is use stock_fin.get_data to get historical data. This returns a Pandas dataframe

https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

There are different ways to do this, but the prices are stored in the pandas.DataFrame.values. You can find prices for previous days there.

I know this doesn't solve the get_live_price issue, mainly because there is no live price to be gotten. I don't expect a fix to be made for this anytime soon, its not a bug
